import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header/TheHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ресторан "Нелли"',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="App">
          <div className="bg-color">
            <div className="menu">
            <Header />
            <main>
              {children}
            </main>
        </div>
      </div>
    </div>
      </body>
    </html>
  )
}
